# Lab_14_Module_2_Intro_to_Scipy

# Challenge 1 - The stats Submodule

In [2]:
import pandas as pd
from scipy import stats
import numpy as np
projects = pd.read_csv(r'C:\Users\Mtime\OneDrive\Bureau\projects.csv')
projects.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

1.1.Import the mode function from scipy.stats and find the mode of the country and currency column.

In [3]:
stats.mode(projects['country'])

ModeResult(mode=array(['US'], dtype=object), count=array([292627]))

In [4]:
stats.mode(projects['currency'])

ModeResult(mode=array(['USD'], dtype=object), count=array([295365]))

1.2. Compute the trimmed mean between 0 and the 75th percentile

In [15]:
from scipy.stats import tmean

x = np.percentile(projects['goal'], 75)
tmean(x)

16000.0

In [6]:
projects['goal_met']=np.where(projects['usd_pledged_real']>projects['usd_goal_real'],1,0)

projects.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,goal_met
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,0
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,0
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,0
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,0
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,0

In [7]:
projects['usd']=np.where(projects['currency']=='USD',1,0)
projects.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,goal_met,usd
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,0,0
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,0,1
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,0,1
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,0,1
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,0,1

In [8]:
crosstab=pd.crosstab(projects['goal_met'],projects['usd'])
crosstab

usd           0       1
goal_met
0         58685  187130
1         24611  108235

In [9]:
from scipy.stats import fisher_exact

oddsratio, pvalue = fisher_exact(crosstab)

print(pvalue)

9.78e-321

# Challenge 2 - The interpolate submodule

In [17]:
from scipy import interpolate

sample = projects.sample(10)
sample

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,goal_met,usd
114399,1581009328,APOTHEOSIS,Video Games,Games,USD,2013-10-09,30000.0,2013-09-09 20:45:53,820.0,failed,37,US,820.00,820.00,30000.00,0,1
279973,494263064,Help Me Make A Book About My Puppy Named Pants...,Children's Books,Publishing,USD,2014-12-19,10000.0,2014-10-20 13:15:06,10.0,failed,1,US,10.00,10.00,10000.00,0,1
128860,165418364,Fruit Biter,Games,Games,USD,2012-08-10,600.0,2012-07-10 19:14:40,1.0,failed,1,US,1.00,1.00,600.00,0,1
240899,295240585,Robert Flaherty Film Seminar presents a free c...,Film & Video,Film & Video,USD,2010-06-22,3000.0,2010-05-19 06:42:15,550.0,failed,14,US,550.00,550.00,3000.00,0,1
22524,1114302914,i-stapps: Active gaming platform for IOS & And...,Gaming Hardware,Games,EUR,2014-07-04,245000.0,2014-05-20 09:28:36,22732.0,failed,52,NL,31154.15,30888.39,332907.57,0,0
223340,2137798531,Kyla's First Full Length CD,Rock,Music,USD,2012-05-18,800.0,2012-03-24 21:13:35,915.0,successful,27,US,915.00,915.00,800.00,1,1
124311,1631095465,VeloStrap - The simple smartphone bike mount,Product Design,Design,USD,2015-11-06,1500.0,2015-10-06 13:34:32,2136.0,successful,98,US,2136.00,2136.00,1500.00,1,1
42492,1216348523,KIWI PLUG - Turn your smartphone into universa...,Gadgets,Technology,EUR,2016-07-07,30000.0,2016-06-07 09:23:57,30280.0,successful,386,FR,34345.86,33520.05,33210.09,1,0
367065,940367639,Tote-Ems Plush Toy Monsters (Canceled),Art,Art,USD,2014-11-14,35000.0,2014-10-15 23:00:06,3467.0,canceled,39,US,3467.00,3467.00,35000.00,0,1
136221,1691698075,"Kingdom of Outcasts, Art Playing Cards by CJ F...",Illustration,Art,USD,2016-12-15,4500.0,2016-11-15 21:13:06,1471.0,failed,19,US,208.00,1471.00,4500.00,0,1

In [19]:
f = interpolate.interp1d(sample.usd_pledged_real, sample.backers)
f

In [20]:

x_new = np.arange(sample.backers.max())
x_new

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385])

In [25]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.plot(x_new, f(x_new))

ValueError: A value in x_new is below the interpolation range.

In [22]:
plt.plot(x_new, g(x_new))

NameError: name 'g' is not defined